# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    open-pull-requests-limit: 10
    directories: [ "/", "/contrib/_aws-vault-proxy/" ] # Locations of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "11:00"
    # Group minor and patch updates
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "thursday"
      time: "11:00"
    # Group minor and patch updates
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
